name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Corre todos los días a la medianoche
  workflow_dispatch:  # También puedes ejecutarlo manualmente desde la pestaña "Actions"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Snake SVG and GIF
        uses: Platane/snk@v3
        with:
          github_user_name: andcarrillo  # Cambia esto si tu nombre de usuario es distinto
          outputs: |
            dist/github-snake.svg?palette=gruvbox-light
            dist/github-snake-dark.svg?palette=gruvbox-dark
            dist/github-snake.gif?color_snake=#BB005D&color_dots=#f0e4ff,#c98eff,#a057dd,#7c2eb3,#4d0075

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

